### PR TITLE
Fixed DOMException issue faced when embedding tfdv visualization in iframe

### PR DESCRIPTION
**Pull request by ajchili**
Solution for #79

### CODE REVIEW

**Comment by caveness** [comment]
Hi Kirin -- Thanks for your contribution! Should this work in a Jupyter notebook? I tried running tfdv.visualize_statistics() in a notebook with this change included, and it looks like it's not displaying the visualization.

**Comment by ajchili** [comment]
This change should work within a Jupyter notebook. I will test it as well to see why this is not working within a notebook.

**Comment by ajchili** [comment]
@caveness are you able to share an example? I was able to use it within a notebook without issue.

For reference, I build tfdv and used it within a notebook like so:
```
!pip install dist/*.whl
import tensorflow_data_validation as tfdv
train_stats = tfdv.generate_statistics_from_csv(data_location=SOURCE)
tfdv.visualize_statistics(train_stats)
```

**Comment by caveness** [comment]
Upon re-testing, we're not seeing an issue, so will merge the PR. Thanks again!

**Pull request merged**
